workflows:
  android-app:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Setup Flutter
        script: |
          flutter doctor
      - name: Go to project directory
        script: |
          cd jiffy # Si tu proyecto está en una subcarpeta llamada 'jiffy'
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
