workflows:
  android-app:
    name: Android Build
    max_build_duration: 60 # Duración máxima de la compilación en minutos
    environment:
      flutter: stable # Usar la versión estable de Flutter
    scripts:
      - name: Set up Flutter
        script: |
          flutter doctor # Verificar el entorno de Flutter
      - name: Get dependencies
        script: |
          flutter pub get # Instalar las dependencias necesarias
      - name: Clean build
        script: |
          flutter clean # Limpiar cualquier archivo temporal de compilación anterior
      - name: Build APK
        script: |
          flutter build apk --release --no-sound-null-safety # Construir el APK en modo release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk # Ruta al archivo APK de la compilación
