workflows:
  android-app:
    name: Android Build
    max_build_duration: 60
    instance_type: Linux
    environment:
      flutter: stable
    scripts:
      - name: Run Flutter clean
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
